### ISSUE TITLE
Error in x$.self$finalize() : attempt to apply non-function

### ISSUE THREAD

**Issue by emilio-berti** [emilio-berti/enerscape#1]
When running on a server cluster, I often get the error:

```
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in (function (x)  : attempt to apply non-function
Error in (function (x)  : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in (function (x)  : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
```

This seems to be an error message due to some Rcpp libraries and that can be ignored: sneumann/xcms#288 and rspatial/terra#30.

**Comment by rhijmans** [comment]
This has now been solved in the development version of Rcpp. This version is scheduled to be released in Jan 2023.

**Comment by emilio-berti** [comment]
Closed for now, I'll re-open if the "bug" still persist.

**Comment by emilio-berti** [comment]
Closed for now, I'll re-open if the "bug" still persist.
