### ISSUE TITLE
Update raster names in vignette

### ISSUE THREAD

**Issue by emilio-berti** [emilio-berti/enerscape#2]
Need to change `rasters$Work` to `rasters$EnergyScape` in all vignettes: [https://emilio-berti.github.io/enerscape.html#landscape-connectivity-for-the-marsican-bear-ursus-arctos-marsicanus-in-the-sirente-velino-regional-park](https://emilio-berti.github.io/enerscape.html#landscape-connectivity-for-the-marsican-bear-ursus-arctos-marsicanus-in-the-sirente-velino-regional-park).

**Comment by flemoal22** [comment]
Thank you Emilio for your fast answers,
Françoise

**Comment by emilio-berti** [comment]
Many things happened. First, _rgeos_, _rgdal_, and thus _raster_ are to be retired in 2023. This makes problematic the dependency with _gdistance_.

This is not the first time I got such dependencies issues and decided to rewrote the core of the package in C++: f4114c0364ae9ea6c595093d4ad1fa5f8a01a8a4.

Since the new release 1.0.0, all backend is in C++ and the only object returned by _enerscape()_ is a SpatRaster (terra). I **finally** wrote a proper vignette, which can be loaded with `vignette("enerscape")`.

@flemoal22 You should be able to install the new version with `devtools::install_github("emilio-berti/enerscape")`. The new version does not have least cost paths analyses, but it's not a big loss, in my opinion. Circuitscape and Omniscape are still there, which I think are a better approach.

P.S. I will upload a new version to CRAN (they actually asked for it due to retiring dependecies) soon.

**Comment by emilio-berti** [comment]
All is good now, closing this.
